version: '3.8'
services:
  main:
    build: .
    ports:
      - '3000:3000'
    networks:
      - webnet
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - webnet
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
networks:
  webnet:
volumes:
  db_data:
